name: My first action test
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to Greeed'
        default: 'Aziz'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        run: echo "Test action 1 - Hello ${{ github.event.inputs.name }}"
      - name: Second interaction
        run: echo "Test action 2 - Bye"

