name: My first action test
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to Greeed'
        default: 'Aziz'
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: GitHub context 
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"      
        
      - name: First interaction Action 1
        run: echo "Test action 1 - Hello ${{ github.event.inputs.name }}"
      - name: First interaction Action 2
        run: echo "Test action 2 - Bye"
  
